### ISSUE TITLE
nefunguje Obor-predmet, zobrazi jen jeden predmet, ikdyž je předmětu 5

### ISSUE THREAD

**Issue by st52487** [Rychleji/x2pd2018#30]
Nejspíše je chyba nekde v tabulce kde se data nevkladají do M:N tabul ci mozna neco s pohledem

**Comment by Rychleji** [comment]
Obor předmět je vazební tabulka, filtruje se podle toho zda přecházíme z předmětu (pak ukazuje obory které mají předmět - většinou bude jen jeden), nebo z oboru (pak ukazuje jaké předměty má daný obor).

Pokud si nic neměnil, pak vím, že v db bylo vskutku pouze 4-5 předmětů ze kterých však pouze jeden byl přiřazený k oboru (IT).
